apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - k8s.iofog.org
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
subjects:
  - kind: ServiceAccount
    name: operator
roleRef:
  kind: Role
  name: operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iofogs.k8s.iofog.org
spec:
  group: k8s.iofog.org
  names:
    kind: IOFog
    listKind: IOFogList
    plural: iofogs
    singular: iofog
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
      labelSelectorPath: .status.labelSelector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      name: operator
  template:
    metadata:
      labels:
        name: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: {{ .Values.operator.image }}
          ports:
            - containerPort: {{ .Values.operator.port }}
              name: metrics
          command:
            - iofog-operator
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "iofog-operator"
